version: "3.9"
services:
  backend:
    build:
      dockerfile: flask-app/Dockerfile
      context: .
    ports:
      - "5000:5000"
  frontend:
    build:
      dockerfile: Frontend/Dockerfile
      context: .
    ports:
    - "80:3000"


